<?php

namespace App\Controllers;

use App\Models\User;
use \Core\View;

/**
 * Dashboard controller
 *
 * PHP version 7.0
 */
class Dashboard extends \Core\Controller
{
    protected function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
        session_start();
        if (isset($_SESSION['permission'])) {
            View::render('Dashboard/index.php', array('code' => $_SESSION['permission']));
            die();
        }
    }

    /**
     * Show the Dashboard for the correct user page
     *
     * @return void
     */
    public function indexAction()
    {
        if (isset($_REQUEST['code'])) {
            $code = filter_input(INPUT_POST, 'code', FILTER_SANITIZE_NUMBER_INT);
            $user = filter_input(INPUT_POST, 'username', FILTER_SANITIZE_STRING);
            $pwd = $_POST['pwd'];
            if (User::signin($user, $pwd)) {
                if ($code == 0) {
                    $_SESSION['permission'] = 0;
                    View::render('Dashboard/index.php', array('code' => $code));
                } else {
                    $_SESSION['permission'] = 1;
                    View::render('Dashboard/index.php', array('code' => $code));
                }

            } else {
                echo "password sbagliata";
            }

        } else {
            echo 'Accesso Negato';
        }


    }


}
